version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  target-branch: main
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
