repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
    exclude: README.md

- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black
    name: Blacken

- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    args: [--count, --show-source, --statistics]
    exclude: setupbase.py
