name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'push-action/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U setuptools
        pip install pre-commit

    - name: Set PY env var
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Test with pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node 13
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python requirements
      run: pip install -r requirements.txt

    - name: Check build and installation of PyPI source distribution
      env:
        SDIST_DIR: sdist_action
      run: |
        python setup.py -v sdist -d ${SDIST_DIR}
        SDIST_FILE=$( ls ${SDIST_DIR}/ )
        ORIGINAL_PWD=$(pwd)

        mkdir -p /tmp/installation_dir
        cd /tmp/installation_dir
        pip install ${ORIGINAL_PWD}/${SDIST_DIR}/${SDIST_FILE}
