name: Publish on PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'CasperWA/ipywidgets-extended' && startsWith(github.ref, 'refs/tags/v')
    env:
      PUBLISH_UPDATE_BRANCH: main
      PY_DIST_DIR: py_dist

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Install Node 13
      uses: actions/setup-node@v2.2.0
      with:
        node-version: '13'

    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Update setuptools and install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Update version and tag
      run: .github/static/update_version.sh

    - name: Push updates to '${{ env.PUBLISH_UPDATE_BRANCH }}'
      uses: CasperWA/push-protected@v2.3.0
      with:
        token: ${{ secrets.RELEASE_PAT }}
        branch: ${{ env.PUBLISH_UPDATE_BRANCH }}
        force: true
        tags: true

    - name: Build source distribution
      run: python setup.py -v sdist -d ${{ env.PY_DIST_DIR }} bdist_wheel -d ${{ env.PY_DIST_DIR }}

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: ${{ env.PY_DIST_DIR }}/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: ${{ env.PY_DIST_DIR }}/
